-- HUD hooks from other addons, it is necessary that the custom HUD was over the background of the menu
LithiumCore.HooksOtherHUD = {
	game = {},
	scores = {},
	title = {},
	titlecard = {},
	intermission = {},
	cont = {},
	playersetup = {}
}

-- List of all hooks, each hook contains all LithCore functions
LithiumCore.Hooks = {
	["IntermissionThinker"] = {},
	["MapChange"] = {},
	["MapLoad"] = {},
	["ThinkFrame"] = {},
	["PreThinkFrame"] = {},
	["PostThinkFrame"] = {},
	["GameQuit"] = {},
	["BotAI"] = {},
	["BotTiccmd"] = {},
	["BotRespawn"] = {},
	["HurtMsg"] = {},
	["NetVars"] = {},
	["PlayerJoin"] = {},
	["PlayerQuit"] = {},
	["PlayerMsg"] = {},
	["TeamSwitch"] = {},
	["ViewpointSwitch"] = {},
	["SeenPlayer"] = {},
	["PlayerThink"] = {},
	["PlayerCanDamage"] = {},
	["PlayerSpawn"] = {},
	["PlayerHeight"] = {},
	["PlayerCanEnterSpinGaps"] = {},
	["ShieldSpawn"] = {},
	["AbilitySpecial"] = {},
	["JumpSpecial"] = {},
	["JumpSpinSpecial"] = {},
	["SpinSpecial"] = {},
	["ShieldSpecial"] = {},
	["MapThingSpawn"] = {},
	["MobjSpawn"] = {},
	["MobjRemoved"] = {},
	["MobjThinker"] = {},
	["MobjFuse"] = {},
	["BossThinker"] = {},
	["ShouldDamage"] = {},
	["MobjDamage"] = {},
	["MobjDeath"] = {},
	["BossDeath"] = {},
	["FollowMobj"] = {},
	["MobjCollide"] = {},
	["MobjLineCollide"] = {},
	["MobjMoveBlocked"] = {},
	["MobjMoveCollide"] = {},
	["TouchSpecial"] = {},
	["MusicChange"] = {},
	["ShouldJingleContinue"] = {},
	["KeyDown"] = {},
	["KeyUp"] = {},
	["PlayerCmd"] = {},
	["HUD"] = {},
	["AddonLoaded"] = {}
}

return true

