-- List of macros that is used in chat
LithiumCore.macrolist = {
	{name = "White", text = {"|white|", "|80"}, color = "\x80"},
	{name = "Magenta", text = {"|magenta|", "|81"}, color = "\x81"},
	{name = "Yellow", text = {"|yellow|", "|82"}, color = "\x82"},
	{name = "Green", text = {"|green|", "|83"}, color = "\x83"},
	{name = "Blue", text = {"|blue|", "|84"}, color = "\x84"},
	{name = "Red", text = {"|red|", "|85"}, color = "\x85"},
	{name = "Grey", text = {"|grey|", "|86"}, color = "\x86"},
	{name = "Orange", text = {"|orange|", "|87"}, color = "\x87"},
	{name = "Sky", text = {"|sky|", "|88"}, color = "\x88"},
	{name = "Purple", text = {"|purple|", "|89"}, color = "\x89"},
	{name = "Aqua", text = {"|aqua|", "|8a"}, color = "\x8A"},
	{name = "Peridot", text = {"|peridot|", "|8b"}, color = "\x8B"},
	{name = "Azure", text = {"|azure|", "|8c"}, color = "\x8C"},
	{name = "Brown", text = {"|brown|", "|8d"}, color = "\x8D"},
	{name = "Rosy", text = {"|rosy|", "|8e"}, color = "\x8E"},
	{name = "Inverted", text = {"|inverted|", "|8f"}, color = "\x8F"},
	
	-- These macros don't work in chat
	{name = "White90", text = {"|white90|", "|90"}, color = "\x90"},
	{name = "Magenta90", text = {"|magenta90|", "|91"}, color = "\x91"},
	{name = "Yellow90", text = {"|yellow90|", "|92"}, color = "\x92"},
	{name = "Green90", text = {"|green90|", "|93"}, color = "\x93"},
	{name = "Blue90", text = {"|blue90|", "|94"}, color = "\x94"},
	{name = "Red90", text = {"|red90|", "|95"}, color = "\x95"},
	{name = "Grey90", text = {"|grey90|", "|96"}, color = "\x96"},
	{name = "Orange90", text = {"|orange90|", "|97"}, color = "\x97"},
	{name = "Sky90", text = {"|sky90|", "|98"}, color = "\x98"},
	{name = "Purple90", text = {"|purple90|", "|99"}, color = "\x99"},
	{name = "Aqua90", text = {"|aqua90|", "|9a"}, color = "\x9A"},
	{name = "Peridot90", text = {"|peridot90|", "|9b"}, color = "\x9B"},
	{name = "Azure90", text = {"|azure90|", "|9c"}, color = "\x9C"},
	{name = "Brown90", text = {"|brown90|", "|9d"}, color = "\x9D"},
	{name = "Rosy90", text = {"|rosy90|", "|9e"}, color = "\x9E"},
	{name = "Inverted90", text = {"|inverted90|", "|9f"}, color = "\x9F"},
	
	{name = "White80", text = {"|white80|", "|a0"}, color = "\xA0"},
	{name = "Magenta80", text = {"|magenta80|", "|a1"}, color = "\xA1"},
	{name = "Yellow80", text = {"|yellow80|", "|a2"}, color = "\xA2"},
	{name = "Green80", text = {"|green80|", "|a3"}, color = "\xA3"},
	{name = "Blue80", text = {"|blue80|", "|a4"}, color = "\xA4"},
	{name = "Red80", text = {"|red80|", "|a5"}, color = "\xA5"},
	{name = "Grey80", text = {"|grey80|", "|a6"}, color = "\xA6"},
	{name = "Orange80", text = {"|orange80|", "|a7"}, color = "\xA7"},
	{name = "Sky80", text = {"|sky80|", "|a8"}, color = "\xA8"},
	{name = "Purple80", text = {"|purple80|", "|a9"}, color = "\xA9"},
	{name = "Aqua80", text = {"|aqua80|", "|aa"}, color = "\xAA"},
	{name = "Peridot80", text = {"|peridot80|", "|ab"}, color = "\xAB"},
	{name = "Azure80", text = {"|azure80|", "|ac"}, color = "\xAC"},
	{name = "Brown80", text = {"|brown80|", "|ad"}, color = "\xAD"},
	{name = "Rosy80", text = {"|rosy80|", "|ae"}, color = "\xAE"},
	{name = "Inverted80", text = {"|inverted80|", "|af"}, color = "\xAF"},
	
	{name = "White70", text = {"|white70|", "|b0"}, color = "\xB0"},
	{name = "Magenta70", text = {"|magenta70|", "|b1"}, color = "\xB1"},
	{name = "Yellow70", text = {"|yellow70|", "|b2"}, color = "\xB2"},
	{name = "Green70", text = {"|green70|", "|b3"}, color = "\xB3"},
	{name = "Blue70", text = {"|blue70|", "|b4"}, color = "\xB4"},
	{name = "Red70", text = {"|red70|", "|b5"}, color = "\xB5"},
	{name = "Grey70", text = {"|grey70|", "|b6"}, color = "\xB6"},
	{name = "Orange70", text = {"|orange70|", "|b7"}, color = "\xB7"},
	{name = "Sky70", text = {"|sky70|", "|b8"}, color = "\xB8"},
	{name = "Purple70", text = {"|purple70|", "|b9"}, color = "\xB9"},
	{name = "Aqua70", text = {"|aqua70|", "|ba"}, color = "\xBA"},
	{name = "Peridot70", text = {"|peridot70|", "|bb"}, color = "\xBB"},
	{name = "Azure70", text = {"|azure70|", "|bc"}, color = "\xBC"},
	{name = "Brown70", text = {"|brown70|", "|bd"}, color = "\xBD"},
	{name = "Rosy70", text = {"|rosy70|", "|be"}, color = "\xBE"},
	{name = "Inverted70", text = {"|inverted70|", "|bf"}, color = "\xBF"},
	
	{name = "White60", text = {"|white60|", "|c0"}, color = "\xC0"},
	{name = "Magenta60", text = {"|magenta60|", "|c1"}, color = "\xC1"},
	{name = "Yellow60", text = {"|yellow60|", "|c2"}, color = "\xC2"},
	{name = "Green60", text = {"|green60|", "|c3"}, color = "\xC3"},
	{name = "Blue60", text = {"|blue60|", "|c4"}, color = "\xC4"},
	{name = "Red60", text = {"|red60|", "|c5"}, color = "\xC5"},
	{name = "Grey60", text = {"|grey60|", "|c6"}, color = "\xC6"},
	{name = "Orange60", text = {"|orange60|", "|c7"}, color = "\xC7"},
	{name = "Sky60", text = {"|sky60|", "|c8"}, color = "\xC8"},
	{name = "Purple60", text = {"|purple60|", "|c9"}, color = "\xC9"},
	{name = "Aqua60", text = {"|aqua60|", "|ca"}, color = "\xCA"},
	{name = "Peridot60", text = {"|peridot60|", "|cb"}, color = "\xCB"},
	{name = "Azure60", text = {"|azure60|", "|cc"}, color = "\xCC"},
	{name = "Brown60", text = {"|brown60|", "|cd"}, color = "\xCD"},
	{name = "Rosy60", text = {"|rosy60|", "|ce"}, color = "\xCE"},
	{name = "Inverted60", text = {"|inverted60|", "|cf"}, color = "\xCF"},
	
	{name = "White50", text = {"|white50|", "|d0"}, color = "\xD0"},
	{name = "Magenta50", text = {"|magenta50|", "|d1"}, color = "\xD1"},
	{name = "Yellow50", text = {"|yellow50|", "|d2"}, color = "\xD2"},
	{name = "Green50", text = {"|green50|", "|d3"}, color = "\xD3"},
	{name = "Blue50", text = {"|blue50|", "|d4"}, color = "\xD4"},
	{name = "Red50", text = {"|red50|", "|d5"}, color = "\xD5"},
	{name = "Grey50", text = {"|grey50|", "|d6"}, color = "\xD6"},
	{name = "Orange50", text = {"|orange50|", "|d7"}, color = "\xD7"},
	{name = "Sky50", text = {"|sky50|", "|d8"}, color = "\xD8"},
	{name = "Purple50", text = {"|purple50|", "|d9"}, color = "\xD9"},
	{name = "Aqua50", text = {"|aqua50|", "|da"}, color = "\xDA"},
	{name = "Peridot50", text = {"|peridot50|", "|db"}, color = "\xDB"},
	{name = "Azure50", text = {"|azure50|", "|dc"}, color = "\xDC"},
	{name = "Brown50", text = {"|brown50|", "|dd"}, color = "\xDD"},
	{name = "Rosy50", text = {"|rosy50|", "|de"}, color = "\xDE"},
	{name = "Inverted50", text = {"|inverted50|", "|df"}, color = "\xDF"},
	
	{name = "White40", text = {"|white40|", "|e0"}, color = "\xE0"},
	{name = "Magenta40", text = {"|magenta40|", "|e1"}, color = "\xE1"},
	{name = "Yellow40", text = {"|yellow40|", "|e2"}, color = "\xE2"},
	{name = "Green40", text = {"|green40|", "|e3"}, color = "\xE3"},
	{name = "Blue40", text = {"|blue40|", "|e4"}, color = "\xE4"},
	{name = "Red40", text = {"|red40|", "|e5"}, color = "\xE5"},
	{name = "Grey40", text = {"|grey40|", "|e6"}, color = "\xE6"},
	{name = "Orange40", text = {"|orange40|", "|e7"}, color = "\xE7"},
	{name = "Sky40", text = {"|sky40|", "|e8"}, color = "\xE8"},
	{name = "Purple40", text = {"|purple40|", "|e9"}, color = "\xE9"},
	{name = "Aqua40", text = {"|aqua40|", "|ea"}, color = "\xEA"},
	{name = "Peridot40", text = {"|peridot40|", "|eb"}, color = "\xEB"},
	{name = "Azure40", text = {"|azure40|", "|ec"}, color = "\xEC"},
	{name = "Brown40", text = {"|brown40|", "|ed"}, color = "\xED"},
	{name = "Rosy40", text = {"|rosy40|", "|ee"}, color = "\xEE"},
	{name = "Inverted40", text = {"|inverted40|", "|ef"}, color = "\xEF"},
	
	{name = "White30", text = {"|white30|", "|f0"}, color = "\xF0"},
	{name = "Magenta30", text = {"|magenta30|", "|f1"}, color = "\xF1"},
	{name = "Yellow30", text = {"|yellow30|", "|f2"}, color = "\xF2"},
	{name = "Green30", text = {"|green30|", "|f3"}, color = "\xF3"},
	{name = "Blue30", text = {"|blue30|", "|f4"}, color = "\xF4"},
	{name = "Red30", text = {"|red30|", "|f5"}, color = "\xF5"},
	{name = "Grey30", text = {"|grey30|", "|f6"}, color = "\xF6"},
	{name = "Orange30", text = {"|orange30|", "|f7"}, color = "\xF7"},
	{name = "Sky30", text = {"|sky30|", "|f8"}, color = "\xF8"},
	{name = "Purple30", text = {"|purple30|", "|f9"}, color = "\xF9"},
	{name = "Aqua30", text = {"|aqua30|", "|fa"}, color = "\xFA"},
	{name = "Peridot30", text = {"|peridot30|", "|fb"}, color = "\xFB"},
	{name = "Azure30", text = {"|azure30|", "|fc"}, color = "\xFC"},
	{name = "Brown30", text = {"|brown30|", "|fd"}, color = "\xFD"},
	{name = "Rosy30", text = {"|rosy30|", "|fe"}, color = "\xFE"},
	{name = "Inverted30", text = {"|inverted30|", "|ff"}, color = "\xFF"}

}

return true
