name: Build PK3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create PK3 file
        run: |
          mkdir -p output
          zip -r output/LithiumCore.pk3 * -x ".git*" -x ".github/*" -x "output/*"

      - name: Upload PK3 artifact
        uses: actions/upload-artifact@v4
        with:
          name: LithiumCore
          path: output/LithiumCore.pk3
